### ISSUE TITLE
Code review morning standup 04/13/2021

### ISSUE THREAD

**Issue by notlfish** [MaiRizk/Newsweek#2]

**Comment by petudeveloper** [comment]
Great work so far.. The header looks good. The detail of the red part in the header gives a plus to the looking of the project.

Remember to put the bootstrap link before the other css links.

**Comment by alexandermorales-dev** [comment]
Looking great!

You may want to avoid using !important in your styles sheet!

**Comment by notlfish** [comment]
You're doing great so far, quite ahead of time! 
Do mind that the fonts Roboto are specified in the css file, but they don't seem to be linked. Look for the import command on google fonts.

**Comment by ad9311** [comment]
Thank you guys. We have followed your suggestions and made the changes.
