### ISSUE TITLE
Morning Session - Stand-Up Meeting  - 14/4

### ISSUE THREAD

**Issue by omar-labana** [MaiRizk/Newsweek#6]
Clean structure, Good job with the ordering.

**Comment by enionsouza** [comment]
Great job, Mai! You did very well on this! Congrats!
I would only suggest a minor issue: the image in the Newsletter section at the bottom of the page should be a background image in a div with cover value as background-size

**Comment by IbrohimRasulov** [comment]
The project was done really great! You have managed the things we couldn't find a way to do. I can show a minor error that I noticed: on the navbar, the first menu should shrink as you make the screen smaller. That's not that big mistake anyway
